<?php
/**
 * http://www.tanecn.com
 * 作者: Tanwen
 * 邮箱: 361657055@qq.com
 * 所在地: 广东广州
 * 时间: 2018/3/16 15:57
 */

namespace Tanwencn\Admin\Database\Eloquent;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Option extends Model
{
    protected $fillable = ['name', 'value'];
    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::saved(function ($model) {
            Cache::forget('t_options_' . $model->name);
        });
    }

    public static function findByName(string $name, string $defalut = '')
    {
        $data = Cache::remember('t_options_' . $name, 7200, function () use ($name) {
            try {
                $model = static::query()->where('name', $name)->select('value')->first();
            } catch (\Exception $e) {
                return null;
            }

            return $model && $model->value ? $model->value : null;
        });

        return $data ?: $defalut;
    }
}