<?php
/**
 * http://www.tanecn.com
 * 作者: Tanwen
 * 邮箱: 361657055@qq.com
 * 所在地: 广东广州
 * 时间: 2018/3/16 15:57
 */

namespace Tanwencn\Admin\Database\Eloquent;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class Option extends Model
{
    protected $fillable = ['name', 'value'];
    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::saved(function ($model) {
            Cache::forget('t_options_' . $model->name);
        });
        self::deleted(function ($model) {
            Cache::forget('t_options_' . $model->name);
        });
    }

    public static function findByName(string $name, $defalut = '')
    {
        $data = Cache::rememberForever('t_options_' . $name, function () use ($name) {

            $model = static::query()->where('name', $name)->select('value')->first();

            return $model && $model->value ? $model->value : "";
        });

        return $data ?: $defalut;
    }
}